// <auto-generated />
namespace NumiNumsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MEalDealChoicesorderModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MEalDealChoicesorderModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121736388_MEalDealChoices-orderModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
